source 'https://rubygems.org'

gem 'slack-ruby-bot'
gem 'celluloid-io'
gem 'puma'
gem 'sinatra'
gem 'dotenv', '~> 2.1.1'
gem 'google_drive', :git => 'https://github.com/gimite/google-drive-ruby.git', :ref => '032ea8f48fe8bfbe04cf9f53db38784bcc9aec5b'
gem 'google-api-client', :git => 'https://github.com/google/google-api-ruby-client.git', :ref => '253bc51e0bedfe486974386ee3a8ca4836a0eea2'

group :development, :test do
	gem 'foreman', '~> 0.81'
	gem 'rake', '~> 11.1.2'
end

group :test do
	gem 'rspec'
end