source 'https://rubygems.org'

gem 'sinatra', '~> 1.4.7'
gem 'sinatra-contrib', '~> 1.4.7'
gem 'activerecord', '~> 4.2'
gem 'sinatra-activerecord', '~> 2.0'
gem 'pg', '~> 0.18.4'
gem 'slack-ruby-client', '~> 0.7.2'
gem 'google_drive', '~> 1.0.6'
gem 'faye-websocket', '~> 0.10.3'
gem 'dotenv', '~> 2.1.1'
gem 'puma', '~> 3.4.0'

group :development, :test do
	gem 'foreman', '~> 0.81'
	gem 'rake', '~> 11.1.2'
	gem 'minitest', '~> 5.7'
end

group :test do
	gem 'rspec'
end